### ISSUE TITLE
Exception when playback starts

### ISSUE THREAD

**Issue by OE4AMW** [OE4AMW/cx300-control#3]
Exception occurs, when audio playback starts:
2020-04-26 22:30:55.390 ERROR 3849 --- [cTaskExecutor-1] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected error occurred invoking async method 'public void com.bsmulders.cx300control.hid.event.HidDataEventDistributor.start(org.hid4java.HidDevice)'.

java.lang.NullPointerException: null
        at com.bsmulders.cx300control.cx300.event.CX300AudioEnabledService.lookup(CX300AudioEnabledService.java:22) ~[classes/:na]
        at com.bsmulders.cx300control.cx300.event.CX300EventDistributor.onApplicationEvent(CX300EventDistributor.java:42) ~[classes/:na]
        at com.bsmulders.cx300control.cx300.event.CX300EventDistributor.onApplicationEvent(CX300EventDistributor.java:10) ~[classes/:na]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:400) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:354) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at com.bsmulders.cx300control.hid.event.HidDataEventDistributor.start(HidDataEventDistributor.java:36) ~[classes/:na]
        at com.bsmulders.cx300control.hid.event.HidDataEventDistributor$$FastClassBySpringCGLIB$$ba0398d2.invoke(<generated>) ~[classes/:na]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

Seems that my firmware-version uses different code to indicate "audio is on" ...

**Comment by OE4AMW** [comment]
On present device, the message hex.substring(6, 8))
- contains also Microphone state
- uses different values

Observed meaning:
00: playback false, mic false
01: playback false, mic true
02: playback true, mic false
03: playback true, mic true
